name: wordledict_loader
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  freezed_annotation: ^2.0.3
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  sembast: ^3.2.0+1
  path: ^1.8.1
  path_provider: ^2.0.11
  get_it: ^7.2.0
  equatable: ^2.0.3
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
